edition = "2018"

brace_style                     = "PreferSameLine"
color                           = "Always"
fn_args_layout                  = "Compressed"
fn_single_line                  = true
format_code_in_doc_comments     = true
format_macro_matchers           = true
format_macro_bodies             = true
format_strings                  = true
inline_attribute_width          = 80
max_width                       = 100
merge_imports                   = true
normalize_doc_attributes        = true
reorder_impl_items              = true
reorder_imports                 = true
reorder_modules                 = true
use_field_init_shorthand        = true
use_try_shorthand               = true
where_single_line               = true
wrap_comments                   = true